// <auto-generated />
using System;
using BankingApp.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingApp.Migrations
{
    [DbContext(typeof(BankingContext))]
    partial class BankingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankingApp.Models.Address", b =>
                {
                    b.Property<long>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Address_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AddressId"));

                    b.Property<long>("AccountNo")
                        .HasColumnType("bigint")
                        .HasColumnName("Account_No_FK");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Country");

                    b.Property<string>("DoorNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Door_No");

                    b.Property<long>("PostalCode")
                        .HasColumnType("bigint")
                        .HasColumnName("Postal_Code");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("State");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Street_Name");

                    b.HasKey("AddressId");

                    b.HasIndex("AccountNo");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("BankingApp.Models.Customer", b =>
                {
                    b.Property<long>("AccountNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Account_No");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountNo"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("Phone_Number");

                    b.HasKey("AccountNo");

                    b.ToTable("Customer");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BankingApp.Models.Corporate", b =>
                {
                    b.HasBaseType("BankingApp.Models.Customer");

                    b.Property<int>("CompanyType")
                        .HasColumnType("int")
                        .HasColumnName("Company_Type");

                    b.ToTable("Corporate");
                });

            modelBuilder.Entity("BankingApp.Models.Individual", b =>
                {
                    b.HasBaseType("BankingApp.Models.Customer");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2")
                        .HasColumnName("DOB");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("Gender");

                    b.ToTable("Individual");
                });

            modelBuilder.Entity("BankingApp.Models.Address", b =>
                {
                    b.HasOne("BankingApp.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("AccountNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BankingApp.Models.Customer", b =>
                {
                    b.OwnsOne("BankingApp.Models.FullName", "FullName", b1 =>
                        {
                            b1.Property<long>("CustomerAccountNo")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("First_Name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Last_Name");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Middle_Name");

                            b1.HasKey("CustomerAccountNo");

                            b1.ToTable("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CustomerAccountNo");
                        });

                    b.Navigation("FullName");
                });

            modelBuilder.Entity("BankingApp.Models.Corporate", b =>
                {
                    b.HasOne("BankingApp.Models.Customer", null)
                        .WithOne()
                        .HasForeignKey("BankingApp.Models.Corporate", "AccountNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BankingApp.Models.Individual", b =>
                {
                    b.HasOne("BankingApp.Models.Customer", null)
                        .WithOne()
                        .HasForeignKey("BankingApp.Models.Individual", "AccountNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
